[package]
name = "riscv32i"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
kernel = { path = "../../kernel" }
#e310x = { path = "../../chips/e310x"}
riscvregs = { git = "https://github.com/DieracDelta/riscvregs.git", rev = "2c35ea8"}
